### ISSUE TITLE
Title in readme not properly capitalised

### ISSUE THREAD

**Issue by ajuanjojjj** [Dpmon1/temporary-joke-repository#1]
The title in the readme file is just the repository name. I'd probably be a better idea to have it properly named and displayed on the readme, so people find it more attractive.

Also maybe add different colours to the months as such;
- ![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) `#f03c15`

**Comment by ajuanjojjj** [comment]
This could also be taken into account to add cool colours
https://github.com/github/markup/issues/369#issuecomment-394483061

**Comment by Dpmon1** [comment]
Good Idea with the title. I made it better.

As for the color, I could not find a way to make it look particularly nice using GitHub markdown.
